### ISSUE TITLE
setCursor not working properly.

### ISSUE THREAD

**Issue by tavdog** [adafruit/Adafruit_EPD#10]
With the Huzzah8266 and EPD Featherwing: calling the two functions one after another but the X position in setcursor is wrong in the first function (upper red text)  and correct in the second (lower red text).

>void display_dir(String s) {
  Serial.println(s);
  epd.setFont(&FreeMonoBold12pt7b);
  epd.setCursor(10, 0);
  epd.setTextColor(EPD_RED);
  epd.print(s);  
}
void display_swell(String s) {
  Serial.println(s);
  epd.setFont(&FreeMonoBold12pt7b);
  epd.setCursor(10, 90);
  epd.setTextColor(EPD_RED);
  epd.print(s); 
}
<img width="387" alt="Screen Shot 2019-04-12 at 12 Fri 11 28 09 AM" src="https://user-images.githubusercontent.com/8324295/56078251-a4e2c480-5d81-11e9-8a29-6f09c7611213.png">

**Comment by caternuson** [comment]
Cross ref:
https://forums.adafruit.com/viewtopic.php?f=57&t=150386

**Comment by ladyada** [comment]
@tavdog hmm does it work with the built in font? this would be a bug in GFX not eink i think

**Comment by tavdog** [comment]
I narrowed this down to  a leading "\n" in the string.  So if there is a new line the string it brings the cursor back to the edge of the screen I guess.
