### ISSUE TITLE
adafruit flexible 2.13'' epd not working

### ISSUE THREAD

**Issue by waggykitty** [adafruit/Adafruit_EPD#12]
I'm trying to use the Adafruit flexible 2.13'' epd on the particle xenon with the Adafruit_EPD_RX and Adafruit_GFX_RX library but the screen doesn't display the text. It flickers when I use the display method but it doesn't display the text or lines that I want it to. I was wondering if anyone might be able to help? attached is my .ino file.
[Xenon_screen_test.zip](https://github.com/adafruit/Adafruit_EPD/files/3340688/Xenon_screen_test.zip)

**Comment by ladyada** [comment]
please use the exact examples we have here in this library for testing to verify your setup, before creating your own custom versions
