### ISSUE TITLE
Is the monochrome 1.54" version supported?

### ISSUE THREAD

**Issue by nic-hartley** [adafruit/Adafruit_EPD#13]
specifically, this one: https://www.adafruit.com/product/4196

I see a whole bunch of model numbers supported, but none of those match any numbers I see on the product.

It might be useful to edit the README to list all the supported products, and a mapping from the product name or SKU to the model number.

**Comment by ladyada** [comment]
yep
https://github.com/adafruit/Adafruit_EPD/blob/master/examples/graphicstest/graphicstest.ino#L22
