### ISSUE TITLE
FeatherWingTest drawBMP setting location not working

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_EPD#15]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=57&t=159450

Maybe add the x,y offsets here?
https://github.com/adafruit/Adafruit_EPD/blob/805921829fa7e812eb5ccbd134d99b50fb06050e/examples/FeatherWingTest/FeatherWingTest.ino#L234

**Comment by ladyada** [comment]
have them try
https://github.com/adafruit/Adafruit_ImageReader
?

**Comment by caternuson** [comment]
@makermelissa does the `FeatherWingTest` example in this repo need updating as well? Or maybe just removed in favor of something in the ImageReader repo?

**Comment by makermelissa** [comment]
I think probably removed in favor of the ImageReader repo. I think the EInkBreakout should be able to do feathers as well, but I'd have to double check that.

**Comment by ladyada** [comment]
yah plz remove here - imagereader is our canonical image-to-display library!

**Comment by caternuson** [comment]
ok @makermelissa can you make that PR? since it sounds like maybe you want to test some things.

**Comment by makermelissa** [comment]
Yes, should be easy enough.

**Comment by makermelissa** [comment]
Ok, after looking at it, I'm going to make 2 PRs:
1. Add a new EInkFeatherWing test to ImageReader so the breakout one doesn't get messy.
2. Remove any examples in this library that draw bitmaps.

**Comment by ladyada** [comment]
sounds like a good plan!
