### ISSUE TITLE
When overlaying shapes, red pixels are not overwritten

### ISSUE THREAD

**Issue by kDCYorke** [adafruit/Adafruit_EPD#21]
May be related to #11 

Code example:

```
#include <Adafruit_GFX.h>
#include <Adafruit_EPD.h>

Adafruit_IL0373 display(152, 152, 1, PIN_A3, 0, -1, -1, &SPI1);

void setup() {
  display.begin();

  display.clearBuffer();
  display.fillScreen(EPD_WHITE);

  // Vertical black bar
  display.fillRect(61, 0, 30, 152, EPD_BLACK);

  // Horizontal red bar overlays
  display.fillRect(0, 61, 152, 30, EPD_RED);

  // Vertical black should overlay but doesn't
  display.fillRect(15, 15, 30, 122, EPD_BLACK);

  display.display();
}

void loop() {
  delay(500);
}
```

When running the above sketch, the smaller black bar shows behind the red bar even though it was added afterwards.

Expected:
![expected](https://user-images.githubusercontent.com/2915320/74874121-6701e580-532e-11ea-98af-070c124a2f47.png)

Actual:
![actual](https://user-images.githubusercontent.com/2915320/74874131-6c5f3000-532e-11ea-8f71-19bf2f2b9ecc.png)

There are two buffers, one for black and one for red. The red gets sent to the screen after the black. The pixel is being set on the color buffer. Then the pixel is set on the black, but it is never cleared on the color. The black buffer is sent, but then the color buffer gets sent and overwrites the pixel.

**Comment by caternuson** [comment]
This might be same as #11

**Comment by kDCYorke** [comment]
I think it is. I’ve submitted a PR that fixes both.

Kai

**Comment by ladyada** [comment]
fixed recently in refactor
