### ISSUE TITLE
Mixed var types misbehaving in Adafruit_EPD::EPD_commandList

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_EPD#32]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=47&t=171658

Something appears to be incorrect with the IL0373 init code definition:
https://github.com/adafruit/Adafruit_EPD/blob/fe9bbed9b8665941ad8d0d597778fd4b7cb28a38/src/drivers/Adafruit_IL0373.cpp#L8-L18

~~The `IL0373_POWER_ON` line specifies 0 parameters. The next line effectively sends command `0xFF` and specifies `200` parameters, which is beyond the hardwired 64 byte `buf` in `EPD_commandList`. Similar issue near the end for the line `0xFF, 20`. There are not 20 actual parameters specified.~~

**Comment by caternuson** [comment]
Wait, just noticed `0xFF` is a special command:
https://github.com/adafruit/Adafruit_EPD/blob/fe9bbed9b8665941ad8d0d597778fd4b7cb28a38/src/Adafruit_EPD.cpp#L500-L504

:thinking:

**Comment by caternuson** [comment]
Don't have hardware to test, but suspecting something with the mix of `uint8_t`, `char` and `int`.

Could `cmd` and `num_args` both be made of type `uint8_t` here?
https://github.com/adafruit/Adafruit_EPD/blob/fe9bbed9b8665941ad8d0d597778fd4b7cb28a38/src/Adafruit_EPD.cpp#L496-L498

**Comment by anven** [comment]
I changed the type to uint8_t - behavior did change, but still nor working. Now it gets hung up on "Waiting...."

Adafruit EPD test
set pins
hard reset
busy
done!
	Command: 0x50
	Data: 0x17, 
	Command: 0x82
	Data: 
	Command: 0x2
Flexible config
Text - Buffer clear
Text - Refresh display
  Powering Up
	Command: 0x1
	Data: 0x3, 0x0, 0x2B, 0x2B, 0x9, 
	Command: 0x6
	Data: 0x17, 0x17, 0x17, 
	Command: 0x4
	Data: 
Waiting...

**Comment by caternuson** [comment]
Something else may be happening now. But I think the results of that change indicate that the mixed variable types is causing an issue.

**Issue name changed to reflect that.**
