### ISSUE TITLE
Release 4.* dropped EPD_INVERSE

### ISSUE THREAD

**Issue by ruoso** [adafruit/Adafruit_EPD#33]
I don't know if that was intentional or not, but it doesn't match current version in master, and I don't see an explanation anywhere for the difference.

**Comment by ladyada** [comment]
yeah it isnt really a useful concept once you have grayscale or tricolor displays.... and no other GFX displays have such a thing. please use the defined colors :)

**Comment by ruoso** [comment]
Cool, thanks for clarifying, may be worth getting the master branch updated to match that.

**Comment by ruoso** [comment]
wait, I don't see it now. I'm very confused.
