### ISSUE TITLE
Getting RED instead of BLACK with PID 4229

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_EPD#47]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=47&t=175386

Seems to be working, but black is showing up as red.

Using a 2.7" Tri-Color eInk / ePaper Shield (PID 4229):
https://www.adafruit.com/product/4229

**Comment by ladyada** [comment]
@makermelissa should probably update the example code to use ThinkInk definitions, and test/verify

**Comment by makermelissa** [comment]
Yeah, for sure.

**Comment by makermelissa** [comment]
Ok, so it turns out I had the CS and DC pins backwards as well as the SRAM CS pin wrong. After fixing those I am getting something that makes sense, except all white is coming through as red for me, everything else looks fine.

**Comment by makermelissa** [comment]
Oh, red and black may be backwards as well. I haven't verified it.
