### ISSUE TITLE
int8_t is limiting the pins that can be used with the library.

### ISSUE THREAD

**Issue by mirzafahad** [adafruit/Adafruit_EPD#60]
This is not an issue per se.

I recently picked up an STM board and tried to convert one of my Adafruit EPD projects for that. The issue is the pins I am using can not be fit in an `int8_t`. For example, I am using a pin PB13, and according to STMduino that equals `205`,  which turns out to be `-51` in an `int8_t`.

I cannot change the pins, because the board is already manufactured. I guess for now I will have a local copy of the library where all the pins are changed to `int16_t`.

Let me know if there is a better way to handle this. 

Thanks in advance.

**Comment by ladyada** [comment]
ok want to try a PR to change the pins to int16_t?
